services:
  app1:
    container_name: app1
    build:
      context: .
      dockerfile: dockerfile
    image: uv:1
    ports:
      - 8301:8000
    networks:
      - my-bridge
    depends_on:
      - mariadb
      - kafka
      - redis
    working_dir: /workspace
    volumes:
      - ./app1/main.py:/workspace/main.py:rw
      - ./app1/src:/workspace/src:rw
      - ./app1/pyproject.toml:/workspace/pyproject.toml:ro
      - ./app1/uv.lock:/workspace/uv.lock:rw
      - ./app1/.env:/workspace/.env:rw
      - uploads:/workspace/uploads:rw
    command: ["sleep", "infinity"]

  app2:
    container_name: app2
    image: uv:1
    ports:
      - 8302:8000
    networks:
      - my-bridge
    depends_on:
      - mariadb
      - kafka
      - redis
    working_dir: /workspace
    volumes:
      - ./app2/main.py:/workspace/main.py:rw
      - ./app2/src:/workspace/src:rw
      - ./app2/pyproject.toml:/workspace/pyproject.toml:ro
      - ./app2/uv.lock:/workspace/uv.lock:rw
      - ./app2/.env:/workspace/.env:rw
    command: ["sleep", "infinity"]

  app3:
    container_name: app3
    image: node:24.13.0
    ports:
      - 8300:5173
    networks:
      - my-bridge
    working_dir: /workspace
    volumes:
      - ./app3/public:/workspace/public:ro
      - ./app3/src:/workspace/src:rw
      - ./app3/eslint.config.js:/workspace/eslint.config.js:ro
      - ./app3/index.html:/workspace/index.html:ro
      - ./app3/package.json:/workspace/package.json:ro
      - ./app3/vite.config.js:/workspace/vite.config.js:ro
      - ./app3/.env:/workspace/.env:rw
    command: ["sleep", "infinity"]
  
  mariadb:
    container_name: mariadb3
    image: mariadb:12.1.2
    restart: always
    ports:
      - 8306:3306
    networks:
      - my-bridge
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d:ro
      - mysql:/var/lib/mysql:rw
    environment:
      - MARIADB_HOST=localhost
      - MARIADB_PORT=3306
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=mini
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8
  
  kafka:
    container_name: kafka
    image: apache/kafka:4.0.1
    restart: always
    ports:
      - 9092:9092
      - 9094:9094
    networks:
      - my-bridge
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://192.168.0.230:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  redis:
    container_name: redis
    image: redis:8.4.0
    restart: always
    ports:
      - 6379:6379
    networks:
      - my-bridge

networks:
  my-bridge:
    driver: bridge

volumes:
  uploads:
  mysql:
